apiVersion: v1
kind: Service
metadata:
  name: absensi-pembangunan-front
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: absensi-pembangunan-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000