apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    app: db
spec:
  initContainers:
    - name: fetch
      image: mwendler/wget
      command: ["wget","--no-check-certificate","https://gist.githubusercontent.com/robisetiapermadi/264be32db9c86d3871220fd65f2b7101/raw/f3b3515d0ee93ba790c5141941dfb2f84b927307/dump.sql","-O","/docker-entrypoint-initdb.d/dump.sql"]
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: dump
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "17082002"
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: dump
        - mountPath: /var/lib/mysql
          name: dbdata
  volumes:
    - emptyDir: {}
      name: dump
    - emptyDir: {}
      name: dbdata
