apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
        - name: master
          image: obiw/mysql-master:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "17082002"
            - name: MYSQL_REPLICATION_USER
              value: 'obiw'
            - name: MYSQL_REPLICATION_PASSWORD
              value: '17082002'
